### ISSUE TITLE
Create simple manual jail with VNET/static MAC/static IP

### ISSUE THREAD

**Issue by tschettervictor** [DtxdF/AppJail#17]
Greetings, 

Coming from Bastille, CBSD, and iocage Appjail looks promising when it comes to auto deployment of applications and containers. 

However, there are times one may want to deploy a jail that acts similar to a VM.
In Bastille, this was done with `bastille create -V jail 14.0-RELEASE 192.168.1.14/23 em0` to have a jail that functions as it's own isolated little environment. Or if using a bridge `bastille create -B jail 14.0-RELEASE 192.168.1.14/23 bridge0` to attach it to a bridge interface. This would persist the MAC address inside each jails `jail.conf` file as well.

With Appjail I'm really not seeing a way to do this. `appjail jail create` does not seem to have the option of assigning an IP or a MAC. I also need these jails to be able to persist their MAC address. How would I do this using the `jail create` command?

**Comment by DtxdF** [comment]
`appjail-quick(1)` can do that. The online documentation has plenty of examples about what you want. `appjail-jail(1)` `create` is not intended for purposes like the ones the man page states:

> Create a new jail. This subcommand only has the responsibility of creating a jail; It is highly recommended to use appjail-quick(1) unless you know what you are doing.

See `vnet`, `bridge` and `macaddr` options in `appjail-quick(1)`.

**Comment by tschettervictor** [comment]
Ah. I found the man pages. Google was not even displaying them.
https://man.freebsd.org/cgi/man.cgi?query=appjail&apropos=0&sektion=0&manpath=FreeBSD+14.1-RELEASE+and+Ports&arch=default&format=html

**Comment by DtxdF** [comment]
> Ah. I found the man pages. Google was not even displaying them.

From what I understand, new man pages are only built between new FreeBSD releases, that's why 13.4-RELEASE has the new AppJail man pages but other versions do not:

* https://man.freebsd.org/cgi/man.cgi?query=appjail-quick&apropos=0&sektion=0&manpath=FreeBSD+13.4-RELEASE+and+Ports&arch=default&format=html

Although you can simply run `man appjail-quick` in your terminal.

> Does this seem correct?

No, the `ip4` option has no effect with the `bridge` option. Each option may or may not have a requirement to take effect, but this is explained in `appjail-quick(1)`.

I just tried the following and it worked on my system:

```sh
appjail quick jtest \
    overwrite=force \
    start \
    bridge="iface:jext test" \
    dhcp="sb_test" \
    mount_devfs \
    device='include $devfsrules_hide_all' \
    device='include $devfsrules_unhide_basic' \
    device='include $devfsrules_unhide_login' \
    device='path bpf unhide' \
    device='path "bpf*" unhide' \
    macaddr='sb_test:00:34:56:78:54:32'
```

```console
# appjail cmd jexec jtest ifconfig sb_test | grep -Ee 'ether|inet'
        ether 00:34:56:78:54:32
        inet 192.168.1.106 netmask 0xffffff00 broadcast 192.168.1.255
```

>  This also removes the IP from my vtnet0 interface for some reason.

If `vtnet0` is a real interface of your system (I know that this interface is used in virtual machines) you should not use `epair:vtnet0` but `iface:vtnet0`.

**Comment by DtxdF** [comment]
> Great! When should you ever use "epair" as opposed to "iface"?

From `appjail-quick(1)`:

> type: Interface type. Can be either epair or iface. If epair is used, two if_epair(4) interfaces, sa_interface that should be used by the host, and sb_interface that should be used by the jail, are created. If iface is used, an existing interface will be added as a member of bridge.

And

> epair is the default.

---

> What about a static IP?

* https://appjail.readthedocs.io/en/latest/networking/alias/

Of course, this does not use VNET like other options. It simply adds another IP address to an existing interface on your host, so the MAC address corresponds to that interface, which you can change from your host's `rc.conf(5)` file.

But you can use a static IP address and options that use VNET. For the `vnet` option, this should be as easy as:

```sh
appjail quick jtest \
    start \
    overwrite=force \
    vnet=<interface> \
    copydir=$PWD/copydir \
    file=/etc/rc.conf
```

**copydir/etc/rc.conf**:

```
ifconfig_<interface>="inet 192.168.1.154/24"
defaultrouter="192.168.1.1"
```

In the case of the `bridge` option this will not work because the interface is created at runtime after the jail is started. Fortunately, using Makejails it is very easy to automate this process:

```
ARG interface
ARG epair

OPTION overwrite=force
OPTION start
OPTION bridge=iface:${interface} ${epair}

STOP

STAGE start

ARG epair
ARG ip
ARG ether
ARG router?

CMD ifconfig sb_${epair} ether ${ether}
CMD ifconfig sb_${epair} inet ${ip}

RAW if [ -n "${router}" ]; then
        CMD route add default ${router}
RAW fi
```

```sh
appjail makejail -j jtest -- \
    --interface jext \
    --epair test
appjail enable jtest start \
    -s epair=test \
    -s ip=192.168.1.154/24 \
    -s ether=00:34:56:78:54:32 \
    -s router=192.168.1.1
appjail start jtest 
```

```console
# appjail cmd jexec jtest ifconfig sb_test | grep -Ee 'ether|inet'
        ether 00:34:56:78:54:32
        inet 192.168.1.154 netmask 0xffffff00 broadcast 192.168.1.255
```

---

>  Also, is the MAC stored anywhere in a conf file? (If not then this would be a good addition)

In the case of the `macaddr` option, yes, in the `rc.conf(5)` file of the jail.

**Comment by tschettervictor** [comment]
A couple of ideas here.

1. Include "macaddr=<iface>:static" which will create a static MAC for that interface based on the name of the jail. (Make it be the first half of the host, then a hash of the jail name for the second half of the address)

2. Add the option to assign an IP address to a VNET jail like the "alias" mode does.

**Comment by DtxdF** [comment]
The commit 12b0b1416d668ab0fe0924369aa27e7fb05c8cb1 adds the first idea. However, the `static` suboption implemented does not use half of the MAC address of the host interface, instead it is necessary to specify a prefix (which is optional). The MAC address is generated based on the jail name.

The reason the MAC address of the host or interface you specify is not used is because the `macaddr` option may not have access to the interface because some interfaces are generated at runtime, and this adds a little more complexity.

**Comment by DtxdF** [comment]
The second idea has already been implemented:

```sh
appjail quick jtest \
    start \
    overwrite=force \
    bridge="jext test" \
    ifconfig="sb_test:inet 192.168.0.116/24" \
    defaultrouter="192.168.0.1" \
    macaddr=sb_test:static
```

```console
# appjail cmd jexec jtest ifconfig sb_test | grep -Ee 'inet|ether'
        ether de:06:84:cf:36:0d
        inet 192.168.0.116 netmask 0xffffff00 broadcast 192.168.0.255
# appjail cmd jexec jtest route -n get default | grep gateway
    gateway: 192.168.0.1
```

**Comment by tschettervictor** [comment]
Works great. I'm assuming I can now use all this with makejails?

**Comment by DtxdF** [comment]
Yeah, like any other option:

**Makejail**:

```
OPTION start
OPTION overwrite=force
OPTION bridge=jext test
OPTION ifconfig=sb_test:inet 192.168.0.116/24
OPTION defaultrouter=192.168.0.1
OPTION macaddr=sb_test:static
```

```sh
appjail makejail -j jtest
```

**Comment by tschettervictor** [comment]
Havnig some trouble getting a Makejail to run. It seems to build fine, but I can't edit the "tag"

```
appjail makejail \
     -j uptime_kuma \
     -f gh+AppJail-makejails/uptime_kuma \
     -o bridge="iface:vtnet0 myiface" \
     -o macaddr=sb_myiface:static \
     -o ifconfig=sb_myiface:inet 192.168.1.157/23 \
     -o defaultrouter=192.168.0.253 \
     -- --uptime_kuma_tag 14.1
```
I've also tried

```
     -- --uptime_kuma_tag 14.1
     -b uptime_kuma_tag 14.1
     -b uptime_kuma_tag=14.1
     -b uptime_kuma_tag[=14.1]
```

**Comment by DtxdF** [comment]
Quoting is important if you run that command in your shell:

```
appjail makejail \
     -j uptime_kuma \
     -f gh+AppJail-makejails/uptime_kuma \
     -o bridge="iface:vtnet0 myiface" # <--- correct \
     -o macaddr=sb_myiface:static \
     -o ifconfig=sb_myiface:inet 192.168.1.157/23 # <--- missing quote \
     -o defaultrouter=192.168.0.253 \
     -- --uptime_kuma_tag 14.1
```

**Comment by tschettervictor** [comment]
My issue is that I want the 14.1 tag.

**Comment by DtxdF** [comment]
As I said, it is important to quote the parts that contain spaces. In your case, the rest of the arguments are not passed to `appjail-makejail(1)` so even changing `--uptime_kuma_tag` to any other value, this will not change. Try this and you will see that it works as expected:

```sh
appjail makejail \
     -j uptime_kuma \
     -f gh+AppJail-makejails/uptime_kuma \
     -o bridge="iface:vtnet0 myiface" \
     -o macaddr=sb_myiface:static \
     -o ifconfig="sb_myiface:inet 192.168.1.157/23" \
     -o defaultrouter=192.168.0.253 \
     -- --uptime_kuma_tag 14.1
```

**diff**:

```diff
--- a.sh        2024-11-29 23:46:33.974761000 -0400
+++ b.sh        2024-11-29 23:46:43.365000000 -0400
@@ -3,6 +3,6 @@
      -f gh+AppJail-makejails/uptime_kuma \
      -o bridge="iface:vtnet0 myiface" \
      -o macaddr=sb_myiface:static \
-     -o ifconfig=sb_myiface:inet 192.168.1.157/23 \
+     -o ifconfig="sb_myiface:inet 192.168.1.157/23" \
      -o defaultrouter=192.168.0.253 \
      -- --uptime_kuma_tag 14.1
```

**Comment by DtxdF** [comment]
As you note, in the `OPTION` instruction in the Makejail I shared with you I am not quoting, this is because that instruction does not require quoting. Makejails are not the same as a shell, AppJail has its own tokenizer for this purpose and transforms the Makejail into a `sh(1)` script called InitScript, but this is off-topic for this issue.

**Comment by tschettervictor** [comment]
Nope. Still using 13.4.

```
appjail makejail \
     -j uptime_kuma \
     -f gh+AppJail-makejails/uptime_kuma \
     -o bridge="iface:vtnet0 myiface" \
     -o macaddr=sb_myiface:static \
     -o ifconfig="sb_myiface:inet 192.168.1.157/23" \
     -o defaultrouter=192.168.0.253 \
     -o boot on \
     -- --uptime_kuma_tag 14.1
```

**Comment by tschettervictor** [comment]
Got it. The “boot on” was the issue.
One more question. Why can’t I do “-b” to specify the tag? The man page seems to suggest that.

**Comment by DtxdF** [comment]
> Also, got my first makejailed app up and running. Uptime-kuma.

Great!

>  One more question. Why can’t I do “-b” to specify the tag? The man page seems to suggest that.

This parameter is used for the “Build Arguments":

* https://appjail.readthedocs.io/en/latest/makejails/arguments-and-build-arguments/

They are not the same as runtime arguments or simply arguments to the Makejail. But the arguments specified with `appjail-makejail(1)` are runtime arguments passed to the `build` stage. Remember that AppJail executes different code at different stages (start, stop, build, etc.).

If you want to know more details about build arguments (not runtime arguments), see “BUILD ARGUMENTS” in `appjail-makejail(5)`.
