### ISSUE TITLE
Man pages could be handy.

### ISSUE THREAD

**Issue by okalm** [DtxdF/AppJail#2]
Hi, 

I installed `appjail` (not the devel package) through pkg on FBSD 13.2 and noticed it comes with a `README.md` but no manual page.
Do you plan to add man pages in the future release ? 
It will be more convenient to read and study, while I appreciate what you've done already with the `README.md`, one big file is not as comfortable as few man pages are, though multiple examples you've put are well explained it's nice to have them.

I am aware of the amount of work you've already done, I just wanted to say thank you for the item in your `todo` list related to `ipfw` , you are right this one need love too. 

Anyway congrats for `appjail` it looks like a great tool to play with, keep up the good work sir :)

**Comment by DtxdF** [comment]
Hi @okalm,

I have no problem adding man pages. Yes, it will take me a lot of time and effort, but I admit that it is very comfortable to read and since AppJail is divided by subcommands it probably won't be too difficult to implement. I will add it in the `TODO`, however, at the moment I am focused on implementing some new AppJail features and creating Makejails.

Thanks!
